[project]
name = "ab-test-analyzer"
version = "0.1.0"
description = "A/B Test Statistical Significance Calculator"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.24.0",
    "plotly>=5.18.0",
    "scipy>=1.11.0",
    "streamlit>=1.28.0",
]
